"""Rendering (Phase 5).

Turns a validated `WeeklyNote` (from Phase 4) into two representations:
  - a **Doc body** (Markdown) for Google Docs, and
  - an **email body** (plain text) with a placeholder for the Doc link that
    Phase 6 resolves once the Doc exists.

It sanitizes quote text so it can't break formatting, runs a final PII re-scan
over both outputs (a leak blocks delivery), and re-checks the hard constraints
(<=250 words, exactly 3 themes / 3 quotes / 3 actions).
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from review_pulse.models import Theme, WeeklyNote
from review_pulse.pipeline.pii import contains_pii
from review_pulse.pipeline.validators import MAX_WORDS, note_text, word_count

if TYPE_CHECKING:
    from review_pulse.config import RunConfig

logger = logging.getLogger(__name__)

# Phase 6 replaces this token in the email body with the real Doc URL.
DOC_LINK_PLACEHOLDER = "{{DOC_URL}}"

_STORE_DISPLAY = {"app_store": "App Store", "play_store": "Play Store"}


@dataclass
class RenderedNote:
    """Both representations of the weekly note plus a delivery gate."""

    doc_body: str = ""
    email_body: str = ""
    subject: str = ""
    # False when a PII leak or a broken constraint should block delivery.
    ok: bool = True
    issues: list[str] = field(default_factory=list)


def _flatten(text: str) -> str:
    """Collapse newlines/whitespace to single spaces so quotes stay one line."""
    return re.sub(r"\s+", " ", (text or "")).strip()


def _md_escape(text: str) -> str:
    """Escape Markdown-significant characters in free text (quotes)."""
    flat = _flatten(text)
    return re.sub(r"([\\`*_{}\[\]()#+\-!|>])", r"\\\1", flat)


def _store_label(store: str | None) -> str:
    if not store:
        return ""
    return _STORE_DISPLAY.get(store, store.replace("_", " ").title())


def _quote_meta(themes: list[Theme] | None) -> dict[str, tuple[str | None, int | None]]:
    """Map candidate-quote text -> (store, rating) for optional attribution."""
    meta: dict[str, tuple[str | None, int | None]] = {}
    for theme in themes or []:
        for quote in theme.quotes:
            meta[quote.text.strip()] = (quote.store, quote.rating)
    return meta


def _attribution(quote: str, meta: dict[str, tuple[str | None, int | None]]) -> str:
    """Return a ' — Store, N★' suffix for a quote when metadata is available."""
    q = quote.strip()
    store, rating = meta.get(q, (None, None))
    if store is None and rating is None:
        # The emitted quote may be a verbatim substring of a candidate.
        for text, (s, r) in meta.items():
            if q and q in text:
                store, rating = s, r
                break
    bits = [b for b in (_store_label(store), f"{rating}\u2605" if rating else "") if b]
    return f" \u2014 {', '.join(bits)}" if bits else ""


def _render_doc(note: WeeklyNote, meta: dict[str, tuple[str | None, int | None]]) -> str:
    lines: list[str] = [f"# {note.product} \u2014 Weekly Review Pulse ({note.week_of})", ""]
    if note.generated_by == "fallback":
        lines += ["_Generated by a deterministic template (no LLM)._", ""]

    lines.append("## Top Themes")
    for i, theme in enumerate(note.themes, start=1):
        stat = f" _({_flatten(theme.stat)})_" if theme.stat else ""
        lines.append(f"{i}. **{_flatten(theme.name)}** \u2014 {_flatten(theme.summary)}{stat}")
    lines.append("")

    lines.append("## Real User Quotes")
    for quote in note.quotes:
        lines.append(f'> "{_md_escape(quote)}"{_attribution(quote, meta)}')
    lines.append("")

    lines.append("## Action Ideas")
    for action in note.actions:
        lines.append(f"- {_flatten(action)}")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_email(note: WeeklyNote, meta: dict[str, tuple[str | None, int | None]]) -> str:
    lines: list[str] = [f"{note.product} \u2014 Weekly Review Pulse ({note.week_of})", ""]
    if note.generated_by == "fallback":
        lines += ["(Generated by a deterministic template \u2014 no LLM.)", ""]

    lines.append("TOP THEMES")
    for i, theme in enumerate(note.themes, start=1):
        stat = f" ({_flatten(theme.stat)})" if theme.stat else ""
        lines.append(f"  {i}. {_flatten(theme.name)} \u2014 {_flatten(theme.summary)}{stat}")
    lines.append("")

    lines.append("REAL USER QUOTES")
    for quote in note.quotes:
        lines.append(f'  - "{_flatten(quote)}"{_attribution(quote, meta)}')
    lines.append("")

    lines.append("ACTION IDEAS")
    for action in note.actions:
        lines.append(f"  - {_flatten(action)}")
    lines.append("")

    lines.append(f"Full document: {DOC_LINK_PLACEHOLDER}")
    return "\n".join(lines).rstrip() + "\n"


def render(
    note: WeeklyNote | None,
    config: "RunConfig",
    themes: list[Theme] | None = None,
) -> RenderedNote:
    """Render Doc + email bodies from a WeeklyNote and gate delivery.

    `themes` (the Phase 3 top themes) are optional and only used to attribute
    quotes with their originating store/rating.
    """
    if note is None:
        logger.warning("[render] no note to render; blocking delivery")
        return RenderedNote(ok=False, issues=["no weekly note to render"])

    meta = _quote_meta(themes)
    subject = f"{note.product} Weekly Review Pulse \u2014 {note.week_of}"
    doc_body = _render_doc(note, meta)
    email_body = _render_email(note, meta)

    issues: list[str] = []

    # Re-check the hard constraints post-render (defense in depth vs Phase 4).
    if len(note.themes) != 3:
        issues.append(f"expected 3 themes, got {len(note.themes)}")
    if len(note.quotes) != 3:
        issues.append(f"expected 3 quotes, got {len(note.quotes)}")
    if len(note.actions) != 3:
        issues.append(f"expected 3 actions, got {len(note.actions)}")
    wc = word_count(note)
    if wc > MAX_WORDS:
        issues.append(f"note is {wc} words (>{MAX_WORDS})")

    # Final PII safety net over the rendered surface. The Doc-link placeholder
    # is excluded so it can never be mistaken for an identifier.
    scan = note_text(note) + " " + doc_body + " " + email_body.replace(DOC_LINK_PLACEHOLDER, "")
    if contains_pii(scan):
        issues.append("rendered output contains PII")

    ok = not issues
    if not ok:
        logger.warning("[render] blocking delivery: %s", "; ".join(issues))
    else:
        logger.info("[render] rendered note (%d words), delivery-ready", wc)

    return RenderedNote(
        doc_body=doc_body,
        email_body=email_body,
        subject=subject,
        ok=ok,
        issues=issues,
    )
